<?php
/**
 * Author: lf
 * Blog: https://blog.feehi.com
 * Email: job@feehi.com
 * Created at: 2016-03-21 14:40
 */

namespace common\components;

use yii;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;

class BaseActiveField extends \yii\widgets\ActiveField
{
    public function init()
    {
        parent::init();
    }

    /**
     * @inheritdoc
     */
    public function dropDownList($items, $options = [], $generateDefault = true)
    {

        return parent::dropDownList($items, $options);
    }

    /**
     * 图片输入框
     *
     */
    public function imgInput($options = [])
    {
        $this->template = "<div class='img_upload'><div class='img_label'>{label}：</div><div style='width: 50%; float: left;'>{input}{img}\n{error}</div></div>\n{hint}";
        $pic = $this->attribute;
        $src = Yii::$app->request->baseUrl . '/images/none.jpg';
        if ($this->model->$pic != '') {
            $src = $this->model->$pic;
            $temp = parse_url($src);
            $src = isset($temp['host']) ? $src : Yii::$app->request->baseUrl . $src;
        }
        $this->parts['{img}'] = Html::img($src, $options);
        return parent::fileInput($options); // TODO: Change the autogenerated stub
    }

    /**
     * ueditor编辑器
     *
     * @param array $options
     * @return $this
     */
    public function ueditor($options = [])
    {
        if (! isset($options['rows'])) {
            $options['rows'] = 5;
        }
        $options = array_merge($this->inputOptions, $options);
        $this->adjustLabelFor($options);
        $name = isset($options['name']) ? $options['name'] : Html::getInputName($this->model, $this->attribute);
        if (isset($options['value'])) {
            $value = $options['value'];
            unset($options['value']);
        } else {
            $value = Html::getAttributeValue($this->model, $this->attribute);
        }
        if (! array_key_exists('id', $options)) {
            $options['id'] = Html::getInputId($this->model, $this->attribute);
        }

        $this->parts['{input}'] = Ueditor::widget(['content' => $value, 'name' => $name, 'id' => $this->attribute]);

        return $this;
    }

}